Repository rutuja310395/CricketBrowserGame, pull requests merged in 2022-10, with the labels that each got.

#2 Added CSS
  index.css
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 JS File Added
  index.js
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 Added JS For Project
  index.js
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 added the documentation
  README.md
  cric.html
  index.css
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest2022, hacktoberfest-accepted
